<script setup lang="ts">
import { ref, computed } from 'vue'
import { FileText, Copy, Check } from 'lucide-vue-next'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import Breadcrumb from '@/components/Breadcrumb.vue'
import { useSEO } from '@/composables/useSEO'

useSEO({
  title: 'Security Policy Generator - Password, Access, Incident | Formatho',
  description: 'Generate security policies for SOC 2 compliance: password policy, access control policy, and incident response plan. Customize and copy. Free, private, client-side.',
  keywords: ['security policy generator', 'soc 2 policy template', 'password policy generator', 'access control policy', 'incident response plan template'],
  ogType: 'website'
})

const companyName = ref('Your Company')
const policyDate = ref(new Date().toISOString().split('T')[0])
const policyType = ref<'password' | 'access' | 'incident'>('password')
const copied = ref(false)

// Password policy options
const minPasswordLength = ref(12)
const requireUppercase = ref(true)
const requireLowercase = ref(true)
const requireNumbers = ref(true)
const requireSymbols = ref(true)
const passwordExpiryDays = ref(90)
const mfaRequired = ref(true)

// Access control options
const accessReviewFreq = ref('quarterly')
const deprovisionSLA = ref(24)
const roleBasedAccess = ref(true)

// Incident response options
const incidentSevLevels = ref(4)
const notifyTimeframe = ref(72)

const policyContent = computed(() => {
  const common = `# ${companyName.value} — ${policyTitle.value}

**Effective Date:** ${policyDate.value}
**Version:** 1.0
**Owner:** Security Team

---`

  if (policyType.value === 'password') {
    return `${common}

## 1. Purpose

This policy establishes requirements for creating, managing, and protecting passwords and authentication credentials across all systems operated by ${companyName.value}.

## 2. Password Requirements

All user passwords must meet the following criteria:

- **Minimum length:** ${minPasswordLength.value} characters
${requireUppercase.value ? '- Must contain at least one uppercase letter (A-Z)\n' : ''}${requireLowercase.value ? '- Must contain at least one lowercase letter (a-z)\n' : ''}${requireNumbers.value ? '- Must contain at least one number (0-9)\n' : ''}${requireSymbols.value ? '- Must contain at least one special character (!@#$%^&*)\n' : ''}- Must not contain the user's name, email, or company name
- Must not match any of the last 12 previously used passwords

## 3. Password Management

- **Password rotation:** Every ${passwordExpiryDays.value} days for privileged accounts
- **Password storage:** Hashed using Argon2id or bcrypt (minimum cost factor 12)
- **Password transmission:** Only over TLS 1.2+ encrypted connections
- **Password sharing:** Prohibited under all circumstances

${mfaRequired.value ? `## 4. Multi-Factor Authentication (MFA)

MFA is **required** for:
- All administrative access
- Remote access to production systems
- Access to systems containing customer data
- Privileged accounts (root, admin, superuser)

Acceptable MFA methods:
- TOTP authenticator apps (Google Authenticator, Authy)
- Hardware security keys (YubiKey, FIDO2)
- Push notification apps with number verification

## 5. Account Lockout` : '## 4. Account Lockout'}

- Accounts lock after 5 consecutive failed login attempts
- Lockout duration: 30 minutes (automatic unlock)
- Administrative unlock requires identity verification

## ${mfaRequired.value ? '6' : '5'}. Enforcement

Violations of this policy may result in:
- Immediate password reset
- Temporary account suspension
- Disciplinary action per company policy

## ${mfaRequired.value ? '7' : '6'}. Review

This policy is reviewed annually or upon significant security changes.

---
*Generated by Formatho — free, privacy-first developer tools.*`
  }

  if (policyType.value === 'access') {
    return `${common}

## 1. Purpose

This policy defines how ${companyName.value} manages access to systems, applications, and data to ensure that only authorized individuals have appropriate access.

## 2. Access Provisioning

- All access requires documented approval from the data owner
- Access is granted based on the principle of least privilege
${roleBasedAccess.value ? '- Role-based access control (RBAC) is enforced across all systems\n' : ''}- Access requests include: requester, system, role level, business justification, and approver
- Temporary access requires an expiration date

## 3. Access Reviews

- Access is reviewed **${accessReviewFreq.value}** for all systems
- Reviews verify: continued business need, appropriate privilege level, and employment status
- Results are documented with remediation actions
- Failed reviews result in immediate access revocation

## 4. Access Revocation

- Access is revoked within **${deprovisionSLA.value} hours** of:
  - Employee termination or resignation
  - Role change that eliminates the need
  - Contract expiration for third parties
- HR notifies IT Security of all terminations
- A deprovisioning checklist ensures all systems are covered

## 5. Privileged Access

- Privileged accounts are separate from standard user accounts
- Privileged access requires MFA
- Privileged sessions are logged
- Break-glass procedures require two-person approval

## 6. Third-Party Access

- Third-party access is time-limited and purpose-restricted
- Third parties sign NDAs and acknowledge security policies
- Sub-processors are reviewed ${accessReviewFreq.value}
- Access is revoked upon contract termination

## 7. Enforcement

Violations may result in access revocation and disciplinary action.

---
*Generated by Formatho — free, privacy-first developer tools.*`
  }

  // Incident response
  return `${common}

## 1. Purpose

This policy establishes the incident response process for ${companyName.value} to detect, respond to, and recover from security incidents affecting the confidentiality, integrity, or availability of systems and data.

## 2. Incident Classification

Incidents are classified into **${incidentSevLevels.value} severity levels:**

| Severity | Description | Response Time | Escalation |
|----------|-------------|---------------|------------|
| SEV-1 (Critical) | Data breach, complete outage, active attack | Immediate | CEO + Legal + All hands |
| SEV-2 (High) | Partial outage, suspected breach, malware | 1 hour | CTO + Security Team |
| SEV-3 (Medium) | Policy violation, misconfiguration, phishing | 4 hours | Security Team |
| SEV-4 (Low) | Scans, failed attempts, minor issues | 24 hours | IT Support |

## 3. Response Process

### 3.1 Detection and Triage
- Monitor alerts from automated systems
- Initial triage within 15 minutes during business hours
- Classify severity and assign incident commander

### 3.2 Containment
- Isolate affected systems
- Preserve evidence (logs, disk images, memory dumps)
- Implement temporary mitigations

### 3.3 Eradication
- Identify root cause
- Remove threat actor access
- Patch vulnerabilities

### 3.4 Recovery
- Restore systems from clean backups
- Verify system integrity
- Monitor for re-infection

### 3.5 Post-Incident
- Conduct lessons-learned within 5 business days
- Document timeline and impact
- Implement preventive measures
- Update this policy as needed

## 4. Notifications

- **Internal:** Incident commander notifies stakeholders based on severity
- **Customers:** Affected customers notified within **${notifyTimeframe.value} hours** for SEV-1 incidents
- **Regulatory:** Breach notifications per applicable laws (GDPR 72h, CCPA, state laws)
- **Law enforcement:** As required by legal counsel

## 5. Communication

- Use out-of-band communication for active incidents
- Never discuss incident details on compromised systems
- Public communications approved by legal and executive team
- Template notifications prepared for common scenarios

## 6. Testing

- Tabletop exercises conducted semi-annually
- Full incident simulation annually
- Results documented with improvement actions

---
*Generated by Formatho — free, privacy-first developer tools.*`
})

const policyTitle = computed(() => {
  if (policyType.value === 'password') return 'Password & Authentication Policy'
  if (policyType.value === 'access') return 'Access Control Policy'
  return 'Incident Response Plan'
})

async function copyPolicy() {
  try {
    await navigator.clipboard.writeText(policyContent.value)
    copied.value = true
    setTimeout(() => (copied.value = false), 1500)
  } catch { /* clipboard unavailable */ }
}
</script>

<template>
  <div class="max-w-5xl mx-auto px-4 py-8">
    <Breadcrumb />
    <div class="flex items-center gap-3 mt-4 mb-6">
      <div class="p-2 bg-primary/10 rounded-lg"><FileText class="w-6 h-6 text-primary" /></div>
      <div>
        <h1 class="text-2xl md:text-3xl font-bold">Security Policy Generator</h1>
        <p class="text-sm text-muted-foreground">Generate SOC 2-ready security policies — customizable and copyable</p>
      </div>
    </div>

    <div class="grid grid-cols-1 lg:grid-cols-2 gap-6">
      <!-- Configuration -->
      <div class="space-y-6">
        <Card>
          <CardHeader><CardTitle class="text-lg">Policy details</CardTitle></CardHeader>
          <CardContent class="space-y-4">
            <div>
              <label class="text-sm font-medium text-muted-foreground mb-1 block">Company name</label>
              <Input v-model="companyName" class="font-mono text-sm" placeholder="Your Company" aria-label="Company name" />
            </div>
            <div>
              <label class="text-sm font-medium text-muted-foreground mb-1 block">Effective date</label>
              <Input v-model="policyDate" type="date" class="font-mono text-sm" aria-label="Effective date" />
            </div>
            <div>
              <label class="text-sm font-medium text-muted-foreground mb-2 block">Policy type</label>
              <div class="flex flex-wrap gap-2">
                <button v-for="pt in [
                  { value: 'password', label: 'Password Policy' },
                  { value: 'access', label: 'Access Control' },
                  { value: 'incident', label: 'Incident Response' },
                ]" :key="pt.value"
                  class="no-btn-hover text-sm px-4 py-2 rounded-lg border transition-colors font-medium"
                  :class="policyType === pt.value ? 'bg-primary/10 border-primary/40' : 'border-border text-muted-foreground'"
                  @click="policyType = pt.value as typeof policyType">
                  {{ pt.label }}
                </button>
              </div>
            </div>
          </CardContent>
        </Card>

        <!-- Policy-specific options -->
        <Card v-if="policyType === 'password'">
          <CardHeader><CardTitle class="text-lg">Password requirements</CardTitle></CardHeader>
          <CardContent class="space-y-3">
            <div>
              <label class="text-sm text-muted-foreground">Minimum length: {{ minPasswordLength }}</label>
              <input type="range" :min="8" :max="20" v-model="minPasswordLength" class="w-full accent-primary" aria-label="Minimum password length" />
            </div>
            <label class="flex items-center gap-2 text-sm"><input type="checkbox" v-model="mfaRequired" class="accent-primary" /> Require MFA section</label>
            <div>
              <label class="text-sm text-muted-foreground">Password expiry (days): {{ passwordExpiryDays }}</label>
              <input type="range" :min="0" :max="180" :step="30" v-model="passwordExpiryDays" class="w-full accent-primary" aria-label="Password expiry days" />
            </div>
          </CardContent>
        </Card>

        <Card v-if="policyType === 'access'">
          <CardHeader><CardTitle class="text-lg">Access control options</CardTitle></CardHeader>
          <CardContent class="space-y-3">
            <div>
              <label class="text-sm text-muted-foreground mb-1 block">Review frequency</label>
              <select v-model="accessReviewFreq" class="w-full h-10 rounded-md border border-input bg-transparent px-3 text-sm">
                <option value="monthly">Monthly</option>
                <option value="quarterly">Quarterly</option>
                <option value="annually">Annually</option>
              </select>
            </div>
            <div>
              <label class="text-sm text-muted-foreground">Deprovisioning SLA: {{ deprovisionSLA }}h</label>
              <input type="range" :min="1" :max="72" v-model="deprovisionSLA" class="w-full accent-primary" aria-label="Deprovisioning SLA hours" />
            </div>
            <label class="flex items-center gap-2 text-sm"><input type="checkbox" v-model="roleBasedAccess" class="accent-primary" /> Include RBAC section</label>
          </CardContent>
        </Card>

        <Card v-if="policyType === 'incident'">
          <CardHeader><CardTitle class="text-lg">Incident response options</CardTitle></CardHeader>
          <CardContent class="space-y-3">
            <div>
              <label class="text-sm text-muted-foreground">Customer notification window: {{ notifyTimeframe }}h</label>
              <input type="range" :min="24" :max="168" :step="24" v-model="notifyTimeframe" class="w-full accent-primary" aria-label="Notification timeframe hours" />
            </div>
          </CardContent>
        </Card>
      </div>

      <!-- Output -->
      <Card>
        <CardHeader class="flex flex-row items-center justify-between space-y-0">
          <CardTitle class="text-lg">Generated policy</CardTitle>
          <Button variant="outline" size="sm" @click="copyPolicy">
            <Check v-if="copied" class="w-3.5 h-3.5 mr-1 text-green-600" /><Copy v-else class="w-3.5 h-3.5 mr-1" />
            {{ copied ? 'Copied' : 'Copy policy' }}
          </Button>
        </CardHeader>
        <CardContent>
          <pre class="text-xs font-mono bg-muted/50 rounded-lg p-4 whitespace-pre-wrap overflow-auto max-h-[600px]">{{ policyContent }}</pre>
        </CardContent>
      </Card>
    </div>
  </div>
</template>
